#!/usr/bin/env bash
#
# Record image digests for release reproducibility (R7 / C-75).
# Writes compose/lock/digests.txt from current pinned tags.
#
# Usage (on release tag, with docker pull access):
#   ./scripts/ci-pin-digests.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

LOCK_DIR="${ROOT_DIR}/compose/lock"
LOCK_FILE="${LOCK_DIR}/digests.txt"
CI_ENV="${ROOT_DIR}/.ci-pin-env"

# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/lib/env-file.sh"
# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/lib/platform.sh"

mkdir -p "${LOCK_DIR}"

cp -f "${ROOT_DIR}/.env.example" "${CI_ENV}"
sed_inplace \
  's|^DATA_DIR=.*|DATA_DIR=/tmp/flixbox-ci-pin/data|; s|^CONFIG_DIR=.*|CONFIG_DIR=/tmp/flixbox-ci-pin/config|' \
  "${CI_ENV}"

cleanup() { rm -f "${CI_ENV}"; }
trap cleanup EXIT

mapfile -t images < <(docker compose --env-file "${CI_ENV}" config --images 2>/dev/null | sort -u)
[[ ${#images[@]} -gt 0 ]] || { echo "No images from compose config" >&2; exit 1; }

{
  echo "# Flixbox image digests — generated by scripts/ci-pin-digests.sh"
  echo "# Date: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo
} >"${LOCK_FILE}"

for img in "${images[@]}"; do
  [[ -n "$img" ]] || continue
  if ! docker pull "$img" >/dev/null 2>&1; then
    echo "WARN: could not pull ${img} — skipping digest" >&2
    echo "${img}  (digest unavailable)" >>"${LOCK_FILE}"
    continue
  fi
  digest="$(docker inspect --format='{{index .RepoDigests 0}}' "$img" 2>/dev/null || true)"
  if [[ -n "$digest" ]]; then
    echo "${digest}" >>"${LOCK_FILE}"
  else
    echo "${img}  (no RepoDigests)" >>"${LOCK_FILE}"
  fi
done

echo "Wrote ${LOCK_FILE} ($(wc -l <"${LOCK_FILE}") lines)"
